name: Custom Notification Workflow

on:
  repository_dispatch:
    types: notify-user
jobs:
  schedule-job:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
            token: ${{ secrets.PAT_TOKEN }}
      - name: Display input data
        run: |
          echo "Email: ${{ github.event.client_payload.email }}"
          echo "Station: ${{ github.event.client_payload.station }}"
          echo "Time: ${{ github.event.client_payload.time }}"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Configure the scheduling for ${{ github.event.client_payload.email }}
        run: |
          ls -la
          python jobs/scheduler.py "${{ github.event.client_payload.email }}" "${{ github.event.client_payload.station }}" "${{ github.event.client_payload.time }}"
      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          git add -A
          git commit -m "job(notify): Add new scheduled workflow for ${{ github.event.client_payload.email }}"
          git push

        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
