
name: Scheduled Notification for emilielalou974@gmail.com
on:
  schedule:
    - cron: "05 15 * * *"
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute script
      run: PYTHONPATH=$(pwd) python jobs/notifier.py "emilielalou974@gmail.com" "Pesaro - Préfecture"
