
name: Scheduled Notification for t@gmail.com
on:
  schedule:
    - cron: "27 21 * * *"
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute script
      run: python jobs/notifier.py "t@gmail.com" "Benjamin Godard - Victor Hugo"
