
name: Scheduled Notification for emilielalou@974@gmail.com
on:
  schedule:
    - cron: "15 14 * * *"
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute script
      run: python jobs/notifier.py "emilielalou@974@gmail.com" "Théâtre des Amandiers - Palais des sports"
